jobs:
  selenium:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v1

      - name: Run Selenium tests
        run: pytest tests/ --maxfail=1 --disable-warnings -q

